### ISSUE TITLE
Updated ic_cdk and candid crates incompatible with SPrincipal type

### ISSUE THREAD

**Issue by saikatdas0790** [seniorjoinu/ic-stable-memory-allocator#10]
Here is the error message I'm seeing

![image](https://user-images.githubusercontent.com/7412443/194802519-fe7312b7-c5f7-4810-ba1a-47e412237d66.png)

Seems to be an incompatibility between the two types. Thoughts?
@seniorjoinu

**Comment by seniorjoinu** [comment]
Gonna fix this soon!
Thanks!

**Comment by seniorjoinu** [comment]
Should be resolved as for `0.4.0-rc1`, but it seems like an ongoing problem with dependencies. There should be a generic solution for this in rust.

**Comment by seniorjoinu** [comment]
Won't close yet, in order to keep it in mind.

**Comment by seniorjoinu** [comment]
No longer actual
