### ISSUE TITLE
Last entry on the btreemap is missing on iter 

### ISSUE THREAD

**Issue by gabrielnic** [seniorjoinu/ic-stable-memory-allocator#19]
Hi @seniorjoinu 

https://github.com/gabrielnic/ic-rust/blob/main/backend/master/src/lib.rs

Based on this btree 

`#[derive(StableType, AsFixedSizeBytes)]
pub struct Db {
  data: SBTreeMap<u64, SBox<Vec<u8>>>,
}`

if you run this commands: 

`build master and install and in order to recreate it run:
dfx canister call master len_val -> should be 0 
dfx canister call master insert 
dfx canister call master len_val -> should be 3
dfx canister call master all 

it should return 3 values but all I get back is 

(
  vec {
    record { 1 : nat64; blob "\01\02\03\04\05\06\07\08\09\0a" };
    record { 2 : nat64; blob "\01\02\03\04\05\06\07\08\09\0a" };
  },
)`

Not really sure what the issue is and why the last element is omitted but see if you can replicate and find out what the issue is.

**Comment by seniorjoinu** [comment]
Fixed and published as 0.4.3
