### ISSUE TITLE
Unable to reinit StableMemoryAllocator - Get this error when upgrading wasm

### ISSUE THREAD

**Issue by saikatdas0790** [seniorjoinu/ic-stable-memory-allocator#3]
![image](https://user-images.githubusercontent.com/7412443/183245410-a41f416a-5063-4a83-ae31-d76d7961e1aa.png)

Here's a minimal reproduction
https://github.com/saikatdas0790/stable_memory_allocator_bug_illustration

Please note I'm on stable rust release. Not sure if that's related

![image](https://user-images.githubusercontent.com/7412443/183245927-966de700-50d4-460a-958a-1717f4324b51.png)

## Steps to Reproduce error

- dfx start
- dfx deploy --no-wallet
- Make a minimal change
- dfx deploy --no-wallet

Let me know if there are any other details I can provide

**Comment by seniorjoinu** [comment]
Hey. 

Great bug report! Thanks.
I've made the fix and released a new v0.2.2 version. I also checked this new version against your repo - it works. 
Please, give it another try and let me know if everything is okay. Feel free to reopen this issue or start a new one!

Thanks again!
