### ISSUE TITLE
Stable BTreeMap benchmark comparison between this lib and dfinity's new offering

### ISSUE THREAD

**Issue by saikatdas0790** [seniorjoinu/ic-stable-memory-allocator#8]
https://github.com/dfinity/stable-structures

Hi @seniorjoinu, would love to see a comparison benchmark between ic-stable-memory's implementation of stable BTreeMap and the one Dfinity recently made available. Thoughts?

**Comment by saikatdas0790** [comment]
@seniorjoinu Any thoughts on this?

**Comment by seniorjoinu** [comment]
ic-stable-memory is slightly faster that ic-stable-structures. Here are the results of a benchmark made by Adam from Dfinity

https://docs.google.com/presentation/d/1B-8Fz6yQx2BUiYdNQ3ZlYTmjuqyBr4VV6pgLQZO_sPo/edit#slide=id.g21c7bc0c394_0_25
