### ISSUE TITLE
Iterate over data in SHashMap?

### ISSUE THREAD

**Issue by saikatdas0790** [seniorjoinu/ic-stable-memory-allocator#9]
I have data in a SHashMap and I've realized that I need to iterate over it. But there's no method that allows me to do so.

Even the std::collection::HashMap has an [iter](https://doc.rust-lang.org/std/collections/hash_map/struct.HashMap.html#method.iter) method that allows this. Any solution for this?

**Comment by seniorjoinu** [comment]
Done for `0.2.4` and for `0.4.0-rc` also.
